-- react boardProject admin 용
SELECT * FROM "MEMBER";

-- 관리자 샘플 회원 데이터 삽입
INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 
			 'admin01@kh.or.kr',
			 '$2a$10$mQuTt31FyF3uXL2qAkF21eZsPnoQP6zeo9pKCevmsWtGJEOsKtFhu',
			 '김관리',
			 '01098765432',
			 NULL,
			 NULL,
			 DEFAULT,
			 DEFAULT,
			 2
);

-- 일반회원 탈퇴 업데이트
UPDATE "MEMBER" SET
MEMBER_DEL_FL = 'Y'
WHERE MEMBER_NO = 1
AND AUTHORITY = 1;

COMMIT;

-- 탈퇴한 일반회원 조회
SELECT MEMBER_NO 
FROM "MEMBER"
WHERE MEMBER_DEL_FL = 'Y'
AND AUTHORITY = 1;



-- 게시글 삭제 업데이트(테스트용)
UPDATE "BOARD" SET
BOARD_DEL_FL = 'Y'
WHERE BOARD_NO = 2000;

COMMIT;



-- 탈퇴하지 않은 전체 일반 회원 수 조회(관리자 제외)
SELECT COUNT(*)
FROM "MEMBER"
WHERE MEMBER_DEL_FL = 'N'
AND AUTHORITY = 1;

-- 일주일 이내 가입한 회원을 조회
SELECT MEMBER_NO, MEMBER_EMAIL, MEMBER_NICKNAME, ENROLL_DATE 
FROM "MEMBER"
WHERE ENROLL_DATE >= SYSDATE - 7
AND AUTHORITY = 1
ORDER BY ENROLL_DATE DESC;

-- 게시글 최대 조회수
SELECT READ_COUNT, BOARD_NO, BOARD_TITLE, MEMBER_NICKNAME
FROM "BOARD"
JOIN "MEMBER" USING(MEMBER_NO)
WHERE READ_COUNT = (SELECT MAX(READ_COUNT) FROM "BOARD");


-- 게시글 최대 좋아요 수
SELECT BOARD_NO, LIKE_COUNT, BOARD_TITLE, MEMBER_NICKNAME
FROM (
	SELECT BOARD_NO, COUNT(*) AS LIKE_COUNT
	FROM BOARD_LIKE
	GROUP BY BOARD_NO
	ORDER BY LIKE_COUNT DESC
)
JOIN "BOARD" USING(BOARD_NO)
JOIN "MEMBER"
USING(MEMBER_NO)
WHERE ROWNUM = 1;


-- 게시글 최대 댓글 수
SELECT BOARD_NO, COMMENT_COUNT, BOARD_TITLE, MEMBER_NICKNAME
FROM (
	SELECT BOARD_NO, COUNT(*) AS COMMENT_COUNT
	FROM "COMMENT"
	GROUP BY BOARD_NO
	ORDER BY COMMENT_COUNT DESC
)
JOIN "BOARD" USING(BOARD_NO)
JOIN "MEMBER"
USING(MEMBER_NO)
WHERE ROWNUM = 1;

-------------------------------------

-- Refresh Token 저장 테이블
CREATE TABLE "TB_REFRESH_TOKEN" (
    "MEMBER_NO" NUMBER PRIMARY KEY,
    "MEMBER_EMAIL" NVARCHAR2(50) NOT NULL,
    "REFRESH_TOKEN" VARCHAR(500) NOT NULL,
    "EXPIRATION_DATE" TIMESTAMP NOT NULL,
    CONSTRAINT "FK_MEMBER_NO" FOREIGN KEY ("MEMBER_NO") 
	REFERENCES "MEMBER" ("MEMBER_NO") 
	ON DELETE CASCADE
);
